[DO NOT MERGE] workspace: bump xla to 20241114.0-f25e9a0
zml/zml pull request #83
Opened 2024-11-14 16:27 UTC by hugomano

- Todo: gather / scatter / todos

2024-11-19 09:30 UTC, gwenzek commented on zml/testing.zig
> +    return _ctx.?.platforms.get(target).?.withCompilationOptions(_test_compile_opts);
this feel not needed. Here is the version I wanted to push:

```
return _ctx.?.autoPlatform().withCompilationOptions(_test_compile_opts);
```

2024-11-19 09:32 UTC, gwenzek approved these changes
thanks, pretty exited about the version bump.

I don't really like the env variable to chose the test runtime see my comment, but beyond that all good for me.

2024-11-19 10:20 UTC, gwenzek requested changes

2024-11-19 10:35 UTC, gwenzek commented on pjrt/pjrt.zig
> +        return state.buf[0..state.buf.len];
this is not correct for when the attribute is not found, because "" isn't a valid version

2024-11-19 10:35 UTC, gwenzek commented on pjrt/pjrt.zig
> +    pub inline fn stableHLOCurrentVersion(self: *const Api) ?[]u8 {
this is weird

not sure I like this global variable set with a once. Maybe move this to the plugin load time ? so we can store it in the Context ?

2024-11-19 10:35 UTC, gwenzek commented on pjrt/pjrt.zig
> +                    _ = std.fmt.bufPrint(&buf, "{d}.{d}.{d}", .{ sliced_version[0], sliced_version[1], sliced_version[2] }) catch unreachable;
this will fail as soon as there is a two number version. Maybe bump it to a bigger buffer ?

2024-11-22 17:14 UTC, hugomano commented
Close in favor of https://github.com/zml/zml/pull/98 because of this ROCm issue in XLA: https://github.com/openxla/xla/issues/19700 

All reviews below are implement in #98

2024-11-22 17:14 UTC, closed without merging